import 'package:flutter/material.dart';
 List <String>colleges=[
  "Sultan Qaboos University",
  "Middle East College",
  "Dhofar University",
  "University of Nizwa",
  "ASharqiyah University",
  "National University of Science and Technology",
 "Muscat University(MU)",
 "Arab Open University",
 "Oman Tourism College",
 "College of Banking and Financial Studies",
  "Global College of Engineering & Technology",
 "Al Musanna College of Technology",
  "Alburaimi University College",
 "Colleges of Applied Sciences at Rustaq, Nizwa, Ibri, Sohar, Sur, Salalah",
  "Fire Safety Engineering College",
 "German University of Technology in Oman(GUtech)",
  "Gulf College of Oman",
  "Higher College of Technology, Al Khuwair",
 "Majan College(University College)",
  "Mazoon College",
 "Modern College of Business and Science",
  "Muscat University College",
  "Nizwa College of Technology",
  "Oman College of Management and Technology",
 "Royal Guard of Oman Technical College",
 "Scientific College of Design",
  "Sohar University",
 "Sur University College",
  "University of Buraimi",
  "Waljat College of Applied Sciences - BITS, Oman",
  "International Maritime College, Sohar Oman",
  "Shinas College of Technology, Shinas Oman",
  "Salalah College of Technology, Salalah Oman",

];